title: Farchan Hakim Raswa
first_name: Farchan
middle_name: Hakim
last_name: Raswa
contact_note: PhD Candidate in CSIE at National Central University, Taiwan.
description: PhD Candidate at NCU CSIE, co-advised by Prof. Jia-Ching Wang and Prof. Chun-Shien Lu.
footer_text: Powered by Jekyll with al-folio theme.
keywords: computer-vision, deep-learning, ncu-csie
lang: en
icon: 🎓

url: https://farchanhakimr.github.io
baseurl: ""
last_updated: false
impressum_path: ""
back_to_top: true

blog_name: Blog
blog_description: My personal academic thoughts.
permalink: /blog/:year/:title/
lsi: false
